version: "3.6"
services:
  core:
    image: "${DHIS2_CORE_IMAGE}"
    container_name: dhis2_core
    restart: always
    volumes:
      - ${DHIS2_CORE_CONFIG:-./config/DHIS2_home/dhis.conf}:${DHIS2_HOME:-/DHIS2_home}/dhis.conf
      - ./config/DHIS2_home/log4j2.xml:${DHIS2_HOME:-/DHIS2_home}/log4j2.xml
      - ./config/server.xml:/usr/local/tomcat/conf/server.xml
      - home:${DHIS2_HOME:-/DHIS2_home}
    environment:
      DHIS2_HOME: ${DHIS2_HOME:-/DHIS2_home}
      CATALINA_OPTS: "-Dcontext.path='${DHIS2_CORE_CONTEXT_PATH:-}' \
              -Dlog4j2.configurationFile=${DHIS2_HOME:-/DHIS2_home}/log4j2.xml"
    depends_on:
      - "db"
    networks:
      - docker_default_network

  db:
    image: "ghcr.io/baosystems/postgis:12-3.3"
    container_name: dhis2_db
    command: "postgres -c max_locks_per_transaction=100"
    restart: always
    volumes:
      - datadb:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: dhis2
      POSTGRES_USER: dhis
      POSTGRES_PASSWORD: dhis
    networks:
      - docker_default_network
  gateway:
    image: "jwilder/nginx-proxy:alpine"
    build:
      context: .
      dockerfile: Dockerfile-gateway
    container_name: gateway
    restart: always
    ports:
      - "${DHIS2_CORE_PORT}:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.apps:/data/apps:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - docker_default_network
  
networks:
  docker_default_network:
    external: false
    name: docker_default_network
volumes:
  datadb:
  home:
  postgres_data:
    external: false
